# Generated by Django 2.0.3 on 2018-04-19 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_sideshow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sideshow',
            name='article_synopsis',
            field=models.CharField(max_length=1000),
        ),
    ]
