# Generated by Django 2.0.3 on 2018-04-29 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_auto_20180429_1720'),
        ('map', '0006_auto_20180429_1417'),
    ]

    operations = [
    ]
