# Generated by Django 2.0.3 on 2018-04-29 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_merge_20180429_1905'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['title', 'location', 'url']},
        ),
        migrations.RemoveField(
            model_name='article',
            name='rating',
        ),
    ]
