# Generated by Django 2.0.3 on 2018-04-29 23:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0008_auto_20180429_1943'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sideshow',
        ),
        migrations.AddField(
            model_name='article',
            name='publish_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Publication date'),
        ),
        migrations.AddField(
            model_name='article',
            name='published_by',
            field=models.CharField(default='Author', max_length=30),
        ),
        migrations.AddField(
            model_name='article',
            name='synopsis',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
