# Generated by Django 2.0.3 on 2018-04-30 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0009_auto_20180429_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='publish_date',
        ),
        migrations.RemoveField(
            model_name='article',
            name='published_by',
        ),
    ]
