# Generated by Django 2.0.3 on 2018-04-30 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0010_auto_20180429_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='article',
            name='lon',
            field=models.FloatField(default=0.0),
        ),
    ]
