entrypoint: '3'
env: flex
runtime: python
entrypoint: gunicorn -b :$PORT wsgi

beta_settings:
    cloud_sql_instances: my-project-411-201600:us-east1:cs411-project
               
runtime_config:
    python_version: 3

    ## MORE TO UPDATE ##
